title: Blackthorn Productions
description: Creative technology solutions by Joe and Kevin Amditis
url: "https://blackthorndevs.com"
baseurl: ""

# Build settings
markdown: kramdown
theme: null

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
